# 640px Patches - No Partial Patches + Overlap Configuration
# MIDOG Dataset preparation for YOLO training

# Patch settings
USE_PATCHES: true
PATCH_SIZE: 640
OVERLAP: 80  # Small overlap to reduce edge data loss while avoiding partial patches
ALLOW_PARTIAL_PATCHES: false  # Skip partial patches to avoid black padding

# Class settings
SINGLE_CLASS: true

# Dataset split settings
INCLUDE_TEST_SET: true
TRAIN_RATIO: 0.7
VAL_RATIO: 0.15

# Patch filtering settings
SKIP_EMPTY_PATCHES: true
OVERLAP_RATIO_THRESHOLD: 0.2  # Lower threshold due to overlap

# File paths
MIDOG_JSON: "MIDOG++.json"
IMAGES_DIR: "datasets/midog_original/images" 