# 480px Patches - Multi Class Configuration
# MIDOG Dataset preparation for YOLO training

# Patch settings
USE_PATCHES: true
PATCH_SIZE: 480
OVERLAP: 0

# Class settings
SINGLE_CLASS: false

# Dataset split settings
INCLUDE_TEST_SET: false

# Patch filtering settings
SKIP_EMPTY_PATCHES: true
OVERLAP_RATIO_THRESHOLD: 0.3

# File paths
MIDOG_JSON: "MIDOG++.json"
IMAGES_DIR: "datasets/midog_original/images" 